#define SUREINPUT_NONE         0
#define SUREINPUT_KEYDOWN      1
#define SUREINPUT_KEYUP        2
#define SUREINPUT_MOUSEMOVE    3
#define SUREINPUT_MBUTDOWN     4
#define SUREINPUT_MBUTUP       5
#define SUREINPUT_SCROLLUP     6
#define SUREINPUT_SCROLLDOWN   7

#define SUREACTION_NONE 0
#define SUREACTION_MOVEFORVARD 1
#define SUREACTION_MOVEBACKWARD 2
#define SUREACTION_MOVELEFT 3
#define SUREACTION_MOVERIGHT 4
#define SUREACTION_SPINLEFT 5
#define SUREACTION_SPINRIGHT 6
#define SUREACTION_ROTATEUP 7
#define SUREACTION_ROTATEDOWN 8
#define SUREACTION_ROTATELEFT 9
#define SUREACTION_ROTATRIGHT 10
#define SUREACTION_ZOOMIN 11
#define SUREACTION_ZOOMOUT 12
#define SUREACTION_MOVEUP 13
#define SUREACTION_MOVEDOWN 14
#define SUREACTION_MINUSITERS 15
#define SUREACTION_PLUSITERS 16
#define SUREACTION_MINUSRECHECKS 17
#define SUREACTION_PLUSRECHECKS 18
#define SUREACTION_MINUSBACKLIGHT 19
#define SUREACTION_PLUSBACKLIGHT 20
#define SUREACTION_DECRASEDEBUG 21
#define SUREACTION_SCREENSHOT 22
#define SUREACTION_TOGGLEMOUSEMOVE 23
#define SUREACTION_TOGGLEPAUSE 24
#define SUREACTION_SAVESTATE 25
#define SUREACTION_LOADSTATE 26
#define SUREACTION_DELETESELECTED 27
#define SUREACTION_TOGGLEMODE 28
#define SUREACTION_MENUSCROLLDOWN 29
#define SUREACTION_MENUSCROLLUP 30
#define SUREACTION_SAVECONTROLS 31
#define SUREACTION_TOGGLESAA 32
#define SUREACTION_PLUSSCALE 33
#define SUREACTION_MINUSSCALE 34
#define SUREACTION_PLUSRAYS 35
#define SUREACTION_MINUSRAYS 36

#define SUREACTIONS_TOTAL 37

#define SUREWINDOW_LABEL 1
#define SUREWINDOW_BUTTON 2
#define SUREWINDOW_NUMBEREDIT 3
#define SUREWINDOW_CHECKBOX 4

#include <SureDefines.h>
#include <SureDefinesCPU.h>
#include <SureGPUData.h>
